### ISSUE TITLE
Metrics Wish List

### ISSUE THREAD

**Issue by dgkf** [pharmaR/riskmetric#8]
**Edit:** _moved each suggestion to individual issues. Please use the [metric project board](https://github.com/pharmaR/riskmetric/projects/1) to track progress and discuss details of each metric in the specified issues, which have now been filed as independent issues (links alongside itemized list)_

_following up on call from Mar. 22nd, 2019 regarding brainstorming_

# Risk Metric Breakdown by Category

### Unit Testing Metrics (see [coverage considerations](#Coverage-Considerations))
- [ ] Unit test coverage #6 
- [ ] Composite coverage of dependencies (average? minimum?) #41

### Documentation Metrics
- [ ] "Documentation Coverage"
   - [ ] Parameter descriptions documented for parameters of exported functions #43
   - [ ] Return object documented for exported functions #43
   - [ ] Example(s) included for exported (un-exported?) functions #43, #44
- [ ] Vignettes #45
- [ ] NEW / NEWS.md / README.md / README.Rmd, etc tracking #46

### Community Engagement
- [ ] Availability of code in a public repository #47
   - [ ] \# of participants in repository issues  #48
   - [ ] Average time-to-response in issues and pull requests #49, #50
   - [ ] \# Watchers / Stars / Forks #51
- [ ] \# downloads (e.g. downloads in last month, 6 months, year, lifetime, etc) #52
- [ ] BugReports target specified in DESCRIPTION

### Maintainability & Reuse
- [ ] \# of active contributors (e.g. active contributors in last 6 months / lifetime) #54
- [ ] \# of author / maintainer contacts (mitigation against getting hit by the metaphorical beer truck) #55
- [ ] License #53

# Prioritization of Metrics
1. Metrics which can be assessed **without source code**
2. Metrics which **require installation of package**
3. Metrics which can be derived with **source code of package alone**
4. Metrics which rely on **source code of package and installation of all dependencies**

---

# Coverage Considerations
Code coverage for validated software becomes a bit more involved than ensuring a single package in isolation runs properly. Looking longterm, we may want to consider a metric that considers the code of dependent code. 

For a hyperbolic example, consider a package which has a single function that re-exports a sophisticated statistical model function. Testing this package to 100% coverage would be trivial, though the underlying code is far more involved. We could then consider all the imported statistical model code as part of the parent package and its code coverage would then be dependent on the code coverage of the imported code. 

To calculate this is non-trivial. We could follow a process like this:
1. Calculate per-expression code coverage with `covr::tally_coverage(by="expression")`
2. Parse expressions for dependency imports
3. Derive per-expression coverage
   a. For expressions with no dependencies, coverage from `covr` can be used
   b. For expressions with dependency, store reference to dependency
4. Build directed graph of package dependencies
5. Walk graph and fill in expression coverage
6. Tally expression coverage for each package export

**Comment by elong0527** [comment]
Thanks @dgkf  for the nice summary. 

For code coverage, I would suggest a weighted average approach. 

code coverage of an R package with dependency = sum( n_line * code coverage) / sum(n_line), where n_line is number of code lines in a dependent R package (including the package itself). 

In this way, we can calculate code coverage in each R package. Then derive this weighted code coverage by using the information available in the database (require to save number of lines in an R package in our database)

**Comment by kkmann** [comment]
good point on dependency aggregated scores - but let's focus on getting stuff done for single packages first and then how to recurse through the dependencies ...

**Comment by kkmann** [comment]
Plot a dependency DAG of all packages in a library?

**Comment by kkmann** [comment]
@dgkf with our latest considerations - shouldn't we reverse the priority listing?

**Comment by dgkf** [comment]
@kkmann - I still think the remote information is the priority for the pharma use case, and will probably provide the quickest gains for the package.

Long term, I think that the priority should shift to the local source-derived metrics, but I fear that it will come with a litany of infrastructural challenges that I'd prefer to brush under the rug when getting things kicked off. Things like non-R dependencies, multiple test frameworks, OS specific behaviors, managing conflicting R package dependencies.

To get something functional off the ground quickly, I think it's best to focus on the remote metrics. However, I don't think one being prioritzed should prevent work in other areas and hopefully keeping the mutli-tiered approach means that we can fallback to other methods until we implement each metric at multiple levels of rigor.

I think that having at least one example of the "top down" (first developing a remote metric without a metric, and then implementing more rigorous methods as needed) and one example of "bottom up" development (first developing a metric based off of a local install/source and by default falling back to this method when possible). Tackling both of these as examples is probably the first priority more generally.

**Comment by matthiazzz** [comment]
Considering the depends/imports of a package is quite important in my opinion. There are packages out there depending on hundreds of additional packages (Surrogate, ...) and using that many additional packages in the background should clearly be flagged as a potential risk. 


I would also propose the following metrics as well

- [ ] Number of reverse dependencies of a package (other packages using the package of interest)
**Reason**: this clearly indicates if a package is widely used in the community. Basic packages such as dplyr have a huge list of these, and it is easy to derive via
`devtools::revdep("dplyr") # currently 1706 reverse "Depends", "Imports", "Suggests" or "LinkingTo", roughly 10% of available CRAN packages!`

- [ ] Age of a package / number of updates to a package
**Reason**: for example, some packages are out there "forever" and do not need frequent updates anymore. Other packages might still get frequent updates, even though they are already very mature.  Another issue might be that very young packages receive a lot of updates after first submission, which might indicate an immature package. Or no updates at all which might also be an issue. How exactly this is used in a metric is open.
Way to derive this is to scrape the "Archive" section of cran/bioconductor. The package "version" does this for CRAN, but this shouldn't be used, it seems bugged as it does not derive some dates correctly (at least for me). 
`install.packages("versions")
versions::available.versions("dplyr")
$`dplyr`
   version       date available
1    0.8.3 2019-07-04      TRUE
2    0.8.2 2019-06-29      TRUE
3  0.8.0.1 2019-02-15      TRUE
4    0.8.0 2019-02-14      TRUE
5    0.7.8 2018-11-10      TRUE
6    0.7.6 2018-06-29      TRUE
7    0.7.4 2017-09-28      TRUE
8    0.7.3 2017-09-09      TRUE
9    0.7.2 2017-07-20      TRUE
10   0.7.1 2017-06-22      TRUE
11   0.7.0 2017-06-09      TRUE
12   0.5.0 2016-06-24      TRUE
13   0.4.3 2015-09-01      TRUE
14   0.4.2 2015-06-16      TRUE
15   0.4.1 2015-01-14      TRUE
16   0.4.0 2015-01-08      TRUE
17   0.1.2 2014-02-24      TRUE
18   0.1.1 2014-01-29     FALSE
19     0.1 2014-01-16     FALSE
20   0.1.3       <NA>        NA
21     0.2       <NA>        NA
22 0.3.0.1       <NA>        NA
23 0.3.0.2       <NA>        NA
24     0.3       <NA>        NA
25   0.7.5       <NA>        NA
26   0.7.7       <NA>        NA
27   0.8.1       <NA>        NA
`
